"""Add role system code

Revision ID: fcaf9d61d401
Revises: 0303d62493ff
Create Date: 2026-02-19 19:09:17.264008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcaf9d61d401'
down_revision: Union[str, Sequence[str], None] = '0303d62493ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('system_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'system_code')
    # ### end Alembic commands ###
